### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by sleipnir** [sile/erl_dist#2]
Hello excellent project. What is the current status of this project?

**Comment by sile** [comment]
Thank you for reaching out.
This project isn't actively developed now.
I can review PRs created by contributors but there is no plan to implement new features myself.

**Comment by sleipnir** [comment]
Thanks for your response.
Sad to hear that it is no longer in development

**Comment by sile** [comment]
😢 

Let me close this issue. If I have an opportunity to resume developing this library in the future, I'll post a comment here.
Anyway, thanks again for finding this library.

**Comment by sleipnir** [comment]
Thanks!
